# Generated by Django 5.2.7 on 2026-04-06 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('pending_tasks', models.PositiveIntegerField(default=0)),
                ('study_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deadline_compliance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('study_sessions_completed', models.PositiveIntegerField(default=0)),
                ('tasks_completed_on_time', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week_start',),
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
