# Generated by Django 5.2.7 on 2026-04-06 14:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=120)),
                ('year_of_study', models.PositiveSmallIntegerField(default=1)),
                ('preferred_study_start_time', models.TimeField(default=datetime.time(18, 0))),
                ('preferred_study_end_time', models.TimeField(default=datetime.time(21, 0))),
                ('daily_study_goal_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('break_duration_minutes', models.PositiveIntegerField(default=15)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_lead_minutes', models.PositiveIntegerField(default=30)),
                ('deadline_reminder_hours', models.PositiveIntegerField(default=24)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
