# Generated by Django 5.2.7 on 2026-04-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='reminder_lead_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
