# Generated by Django 5.2.7 on 2026-04-06 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('subject_code', models.CharField(blank=True, max_length=30)),
                ('instructor_name', models.CharField(blank=True, max_length=120)),
                ('semester', models.CharField(blank=True, max_length=60)),
                ('class_schedule', models.CharField(blank=True, max_length=255)),
                ('color_tag', models.CharField(default='#2C7A7B', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('subject_name',),
                'unique_together': {('user', 'subject_name', 'subject_code')},
            },
        ),
    ]
