# Generated by Django 5.2.7 on 2026-04-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('planner', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='is_active',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='focus_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='prompt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='title',
            field=models.CharField(default='AI Study Plan', max_length=160),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='weekly_hours_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studysession',
            name='session_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='plannersettings',
            name='study_session_reminder_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='assessments.assessment'),
        ),
    ]
